apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: conditar-gui
  labels:
    app: conditar-gui
spec:
  resources:
    requests:
      cpu: 500m
      memory: 4Gi
    limits:
      memory: 8Gi
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      buildArgs:
        - name: CONDITAR_INSECURE_BUILD_NETWORK
          value: "false"
  output:
    to:
      kind: ImageStreamTag
      name: conditar-gui:latest
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
