apiVersion: v1
kind: ConfigMap
metadata:
  name: conditar-gui-config
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  CONDITAR_JOB_ROOT: "/data/jobs"
  CONDITAR_RUNTIME: "openshift_mock"
  CONDITAR_DOCKER_IMAGE: "osuninglab/conditar-dev:2026-07-10"
  CONDITAR_TMP: "/tmp/conditar-gui"
  CONDITAR_OPENSHIFT_JOB_MOUNT: "/data/jobs"
  CONDITAR_OPENSHIFT_PVC: "conditar-gui-jobs"
  CONDITAR_OPENSHIFT_SUBMIT: "false"
  CONDITAR_OPENSHIFT_DEVICE: "cuda:0"
  CONDITAR_OPENSHIFT_GPU_RESOURCE: "nvidia.com/gpu"
  CONDITAR_OPENSHIFT_GPU_COUNT: "1"
  CONDITAR_OPENSHIFT_CPU_REQUEST: "2"
  CONDITAR_OPENSHIFT_MEMORY_REQUEST: "16Gi"
  CONDITAR_OPENSHIFT_MEMORY_LIMIT: "32Gi"
  CONDITAR_OPENSHIFT_IMAGE_PULL_POLICY: "IfNotPresent"
  CONDITAR_SLURM_TIME: "04:00:00"
  CONDITAR_SLURM_MEM: "32G"
  CONDITAR_SLURM_CPUS: "4"
  CONDITAR_SLURM_GPUS: "1"
